// import "./solar"
// import "./gltf"
// import "./buffer-geometry"
// import "./instanced-mesh"
// import "./instancing-with-three-1.1"
// import "./instancing-with-three-1.2"
// import "./instancing-with-three-1.3"
import "./gltf-instancing"
